name: DJANGO CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
    - "main"
  issue_comment:
    branches:
    - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/premuimreal

  deploy-to-server:
    needs: build
    name: Deploy to Production server
    runs-on: ubuntu-latest
    steps:
      - name: logging into remote server with ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRC_HOST_NAME }}
          username: ${{ secrets.PRC_HOST_USERNAME }}
          password: ${{ secrets.PRC_HOST_PASSWORD }}
          port: ${{ secrets.PRC_HOST_PORT }}
          script: |
            /root/cdal-main/deploy_code_changes.py